// js/elements.js — Referencias al DOM
// Este archivo es el único punto donde se definen los selectores del DOM.
// NO importa nada de otros módulos para evitar dependencias circulares.

export const elements = {
    htmlTag: document.documentElement,
    tableContainer: document.getElementById('table-container'),
    paginationControlsBottom: document.getElementById('pagination-controls-bottom'),
    rowCount: document.getElementById('row-count'),
    searchInput: document.getElementById('search-input'),
    addRowBtn: document.getElementById('add-row-btn'),
    deleteRowBtn: document.getElementById('delete-row-btn'),
    manageColsBtn: document.getElementById('manage-cols-btn'),
    exportExcelBtn: document.getElementById('export-excel-btn'),
    importAllBtn: document.getElementById('import-all-btn'),
    importAllInput: document.getElementById('import-all-input'),
    exportAllBtn: document.getElementById('export-all-btn'),
    themeToggle: document.getElementById('theme-toggle'),
    themeToggleDarkIcon: document.getElementById('theme-toggle-dark-icon'),
    themeToggleLightIcon: document.getElementById('theme-toggle-light-icon'),
    templateSelectDropdown: document.getElementById('template-select-dropdown'),
    createTemplateBtn: document.getElementById('create-template-btn'),
    editSelectedTemplateBtn: document.getElementById('edit-selected-template-btn'),
    deleteSelectedTemplateBtn: document.getElementById('delete-selected-template-btn'),
    generatePdfBtn: document.getElementById('generate-pdf-btn'),
    summaryBar: document.getElementById('summary-bar'),
    filtersContainer: document.getElementById('filters-container'),
    toastContainer: document.getElementById('toast-container'),
    templateModal: document.getElementById('template-modal'),
    manualVarsModal: document.getElementById('manual-vars-modal'),
    previewModal: document.getElementById('preview-modal'),
    manageDbBtn: document.getElementById('manage-db-btn'),
    dbModal: document.getElementById('db-modal'),
    columnsModal: document.getElementById('columns-modal'),
    imageUploadModal: document.getElementById('image-upload-modal'),
    temporalModeCheckbox: document.getElementById('temporal-mode-checkbox'),
    loadingOverlay: document.getElementById('loading-overlay'),
    increaseFontSizeBtn: document.getElementById('increase-font-size'),
    decreaseFontSizeBtn: document.getElementById('decrease-font-size'),
    tableFontColorPicker: document.getElementById('table-font-color-picker'),
    selectedRowIdentifierDisplay: document.getElementById('selected-row-identifier-display'),
    // Estos se definen en populateModals()
    promptModal: null,
    confirmModal: null,
};
